FROM python:3.14.4-slim

WORKDIR /app/

RUN pip install torch --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt /app/requirements.txt

RUN pip install -r /app/requirements.txt

COPY config.py /app/config.py
COPY main.py /app/main.py
COPY best_model_checkpoint /app/best_model_checkpoint

EXPOSE 8000

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]